name: CI + Pages Deploy

on:
  pull_request:
  push:
    branches: [main]

env:
  NODE_VERSION: 20

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4            # ← OK
      - uses: actions/setup-node@v4          # ← list-item begins
        with:                                # 2-space indent under “-”
          node-version: ${{ env.NODE_VERSION }}
          cache: npm                         # strings don't need quotes here
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - name: Playwright
        run: |
          npx playwright install --with-deps
          npm run e2e

  build:
    if: github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest

    environment:
      name: github-pages               # fixed name
      url:  ${{ steps.deploy.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci
      - run: npm run build          # creates ./dist

      - id: deploy
        uses: actions/deploy-pages@v2   # picks artifact from same job

